import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.className} ${geistMono.className} antialiased`}
        >
        <div
            className="
            fixed
            top-3
            left-1/2
            -translate-x-1/2
            w-[98%]
            min-h-[3.75rem]
            rounded-2xl
            bg-blue-400/10
            backdrop-blur-[10%]
            z-50
            flex
            justify-between
            items-center
            ps-25
            pe-25
          "
        >
            <Navbar />
        </div>
        <main className="static">
            {children}
        </main>
        </body>
        </html>
    );
}
